### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by FroostySnoowman** [FroostySnoowman/ACDB#1]
**The To-Do List For ACDB**

- [x] Nickname changes modlog.
- [ ] Make message delete modlog log images.
- [ ] Make message edit modlog log images.
- [ ] Role color changes modlog.
- [x] Role name changes modlog.
- [x] Role permission changes modlog.
- [ ] Check if a role permission wasn't added/removed in the permission changes modlog.
- [ ] Role deleted modlog.
- [ ] Role created modlog.
- [ ] Joined VC modlog.
- [ ] Leave VC modlog.
- [ ] Channel permission changes modlog.
- [ ] Channel created modlog.
- [ ] Channel deleted modlog.
- [ ] Category channel created modlog.
- [ ] Category channel deleted modlog.
- [ ] Member banned modlog.
- [x] Member joined modlog.
- [x] Member leave modlog.
- [ ] Member kicked modlog.

**Comment by FroostySnoowman** [comment]
**To-Do List For ACDB Utilities**

- [ ] Suggestions

**Comment by FroostySnoowman** [comment]
**To-Do List For ACDB Mod Commands**

TBD

**Comment by FroostySnoowman** [comment]
**To-Do List For ACDB Ticket System**

- [ ] Make it work
- [ ] Make the transcripts configurable/able to be setup.
- [ ] Make a check that checks if their ticket system was deleted, if so it states an error and deletes the button.

**Comment by FroostySnoowman** [comment]
**To-Do List For ACDB Housekeeping**

- [ ] Organize the code.

**Comment by FroostySnoowman** [comment]
To-Do List For ACDB Owner Only

- [ ] Make commands only work within a sepcific guild and only to specific users.
